In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

dataset = pd.read_csv('weatherHistory.csv')
# dataset.isnull().sum()
# df = dataset.fillna(value=0)
# df.isnull().sum()

In [2]:
dataset.describe()

Temperature (C)  Apparent Temperature (C)      Humidity  \
count     96453.000000              96453.000000  96453.000000   
mean         11.932678                 10.855029      0.734899   
std           9.551546                 10.696847      0.195473   
min         -21.822222                -27.716667      0.000000   
25%           4.688889                  2.311111      0.600000   
50%          12.000000                 12.000000      0.780000   
75%          18.838889                 18.838889      0.890000   
max          39.905556                 39.344444      1.000000   

       Wind Speed (km/h)  Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
count       96453.000000            96453.000000     96453.000000     96453.0   
mean           10.810640              187.509232        10.347325         0.0   
std             6.913571              107.383428         4.192123         0.0   
min             0.000000                0.000000         0.000000         0.0   
25%             5.828200              116.000000         8.339800         0.0   
50%             9.965900              180.000000        10.046400         0.0   
75%            14.135800              290.000000        14.812000         0.0   
max            63.852600              359.000000        16.100000         0.0   

       Pressure (millibars)  
count          96453.000000  
mean            1003.235956  
std              116.969906  
min                0.000000  
25%             1011.900000  
50%             1016.450000  
75%             1021.090000  
max             1046.380000

In [3]:
 dataset.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [4]:
df = dataset.fillna(value=0)

In [5]:
df.isnull().sum()

Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [6]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
df['Precip Type'] = LE.fit_transform(df['Precip Type'].astype(str))

In [7]:
# taking value from precip type 
x=df.iloc[:, 2:12].values
print(x)

[[1 9.47222222222222 7.388888888888887 ... 0.0 1015.13
  'Partly cloudy throughout the day.']
 [1 9.355555555555558 7.227777777777776 ... 0.0 1015.63
  'Partly cloudy throughout the day.']
 [1 9.377777777777778 9.377777777777778 ... 0.0 1015.94
  'Partly cloudy throughout the day.']
 ...
 [1 22.03888888888889 22.03888888888889 ... 0.0 1015.66
  'Partly cloudy starting in the morning.']
 [1 21.522222222222226 21.522222222222226 ... 0.0 1015.95
  'Partly cloudy starting in the morning.']
 [1 20.438888888888894 20.438888888888894 ... 0.0 1016.16
  'Partly cloudy starting in the morning.']]


In [8]:
# column to be predicted
y=df.iloc[:,1].values
print(y)

['Partly Cloudy' 'Partly Cloudy' 'Mostly Cloudy' ... 'Partly Cloudy'
 'Partly Cloudy' 'Partly Cloudy']


In [9]:
x[:,9] = LE.fit_transform(x[:,9])
x = x.astype('int')
print(x)
# level encoding successfully done 

[[   1    9    7 ...    0 1015  197]
 [   1    9    7 ...    0 1015  197]
 [   1    9    9 ...    0 1015  197]
 ...
 [   1   22   22 ...    0 1015  170]
 [   1   21   21 ...    0 1015  170]
 [   1   20   20 ...    0 1016  170]]


In [10]:
# level encoding - column summary
y = LE.fit_transform(y)
print(y)

[19 19 17 ... 19 19 19]


In [11]:
# splitting the values in training part and test part
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)


In [15]:
from sklearn.preprocessing import StandardScaler
stad_scal = StandardScaler()
x_train = stad_scal.fit_transform(x_train)
x_test = stad_scal.fit_transform(x_test)

In [12]:
print(x_train)
print(x_test)

[[   1   15   15 ...    0 1014  111]
 [   1    6    1 ...    0 1010   27]
 [   1   18   18 ...    0 1010  111]
 ...
 [   1    9    7 ...    0 1010  111]
 [   1   19   19 ...    0 1012  132]
 [   1    5    2 ...    0 1015  132]]


In [13]:
print(x_test)

[[   1   28   28 ...    0 1014  197]
 [   1   10    7 ...    0 1017   57]
 [   1   14   14 ...    0 1022  170]
 ...
 [   1   10   10 ...    0 1017  154]
 [   1   24   24 ...    0 1006  197]
 [   1   18   18 ...    0 1016  170]]


In [14]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
clf.score(x_test,y_test)

0.6687056140168991